import os
import logging
import shutil
import asyncio
import datetime
from pathlib import Path
from babeldoc.format.pdf import high_level
from babeldoc.translator.translator import OpenAITranslator
from babeldoc.docvision.table_detection.rapidocr import RapidOCRModel
from babeldoc.format.pdf.translation_config import TranslationConfig, WatermarkOutputMode

from . import common, db, to_translate
from babeldoc.docvision.doclayout import DocLayoutModel

logger = logging.getLogger(__name__)


def clean_output_filename(original_path: Path, output_dir: str) -> Path:
    """Clean redundant suffixes generated by babeldoc"""
    stem = original_path.stem.split('.')[0]
    new_path = Path(output_dir) / f"{stem}{original_path.suffix}"

    # Support all possible output filename variants
    possible_suffixes = [
        '.dual', '.mono',
        '.no_watermark.en.dual', '.no_watermark.en.mono',
        '.en.dual', '.en.mono',
        '.no_watermark.zh.mono', '.no_watermark.zh.dual',
        '.zh.dual', '.zh.mono',
        'no_watermark.zh.dual',
        'no_watermark.en.dual',
        '.no_watermark.zh.mono',
        'no_watermark.zh.mono',
        'no_watermark.zh.mono',
        'no_watermark.en.mono',
        '.no_watermark.en.mono',
        'no_watermark.en.mono',
        'no_watermark.ko.mono',
        'no_watermark.ru.mono',
        'no_watermark.es.mono',
        'no_watermark.pt.mono',
        'no_watermark.fr.mono',
        'no_watermark.it.mono',
        'no_watermark.de.mono',
        'no_watermark.ar.mono',
        'no_watermark.ja.mono'
    ]

    for suffix in possible_suffixes:
        temp_path = Path(output_dir) / f"{stem}{suffix}{original_path.suffix}"
        if temp_path.exists():
            shutil.move(temp_path, new_path)
            logger.info(f"Renamed file: {temp_path} -> {new_path}")
            break

    return new_path if new_path.exists() else None


async def async_translate_pdf(trans):
    """Asynchronous PDF translation core function"""
    try:
        start_time = datetime.datetime.now()
        original_path = Path(trans['file_path'])

        logger.info(f"Starting PDF translation: {original_path}")

        # Initialize translation library
        high_level.init()

        # Convert language code
        target_lang = common.convert_language_name_to_code(trans['lang'])
        logger.info(f"Target language: {target_lang}")

        # Initialize document layout model
        doc_layout_model = DocLayoutModel.load_onnx()
        logger.info("Document layout model loaded")

        # Initialize table model (enabled based on parameter)
        table_model = RapidOCRModel() if trans.get('translate_table', False) else None
        if table_model:
            logger.info("Table recognition model enabled")

        # Create translator instance
        translator = OpenAITranslator(
            lang_in="auto",
            lang_out=target_lang,
            model=trans.get('model', 'gpt-4o-mini'),  # Use more common default model
            api_key=trans['api_key'],
            base_url=trans.get('api_url', 'https://api.openai.com/v1'),
            ignore_cache=False,
        )
        logger.info(f"Translator initialized, model: {trans.get('model', 'gpt-4o-mini')}")

        # Complete translation configuration - fix parameter names and types
        config = TranslationConfig(
            input_file=str(original_path),
            output_dir=str(trans['target_path_dir']),
            translator=translator,
            lang_in="auto",
            lang_out=target_lang,
            doc_layout_model=doc_layout_model,
            watermark_output_mode=WatermarkOutputMode.NoWatermark,
            min_text_length=5,
            pages=None,
            qps=3,
            table_model=table_model,
            no_dual=True,  # Generate only monolingual PDF
            no_mono=False,  # Generate monolingual PDF
            split_short_lines=True,
            skip_clean=True,
            skip_scanned_detection=True,  # Skip scan detection first to improve performance
            debug=trans.get('debug', False),
            # Ensure these parameters exist
            formular_font_pattern=trans.get('formular_font_pattern'),
            formular_char_pattern=trans.get('formular_char_pattern'),
            dual_translate_first=trans.get('dual_translate_first', False),
            disable_rich_text_translate=trans.get('disable_rich_text_translate', False),
            enhance_compatibility=trans.get('enhance_compatibility', False),
            use_alternating_pages_dual=trans.get('use_alternating_pages_dual', False),
            report_interval=0.1,
            custom_system_prompt=trans.get('custom_system_prompt'),
            working_dir=trans.get('working_dir'),
            auto_extract_glossary=trans.get('auto_extract_glossary', False),
            auto_enable_ocr_workaround=trans.get('auto_enable_ocr_workaround', False),
            only_include_translated_page=trans.get('only_include_translated_page', False),
            save_auto_extracted_glossary=trans.get('save_auto_extracted_glossary', False),
            enable_graphic_element_process=not trans.get('disable_graphic_element_process', False),
            merge_alternating_line_numbers=trans.get('merge_alternating_line_numbers', True),
            skip_translation=trans.get('skip_translation', False),
            skip_form_render=trans.get('skip_form_render', False),
            skip_curve_render=trans.get('skip_curve_render', False),
            only_parse_generate_pdf=trans.get('only_parse_generate_pdf', False),
            pool_max_workers=trans.get('pool_max_workers'),
            term_pool_max_workers=trans.get('term_pool_max_workers'),
        )

        logger.info("Starting PDF translation execution...")

        # Execute translation - fix event handling logic
        async for event in high_level.async_translate(config):
            logger.debug(f"Received event: {event}")

            if event["type"] == "progress_update":  # Fix event type
                progress = event.get("overall_progress", 0)
                db.execute(
                    "UPDATE translate SET process=%s WHERE id=%s",
                    int(progress),
                    trans['id']
                )
                logger.info(f"Translation progress: {progress}%")

            elif event["type"] == "finish":
                logger.info("Translation completed")
                # Process output filename
                final_path = clean_output_filename(original_path, trans['target_path_dir'])

                # Update database record
                if final_path and final_path.exists():
                    db.execute(
                        "UPDATE translate SET target_file=%s WHERE id=%s",
                        str(final_path),
                        trans['id']
                    )
                    logger.info(f"Output file: {final_path}")

                # Calculate token usage
                spend_time = (datetime.datetime.now() - start_time).total_seconds()

                # Trigger completion callback
                to_translate.complete(
                    trans,
                    text_count=1,  # PDF counted by file
                    spend_time=spend_time
                )
                return True

            elif event["type"] == "error":
                error_msg = event.get("error", "Unknown error")
                logger.error(f"Error occurred during translation: {error_msg}")
                db.execute(
                    "UPDATE translate SET status='failed', failed_reason=%s WHERE id=%s",
                    str(error_msg), trans['id']
                )
                return False

    except Exception as e:
        logger.error(f"PDF translation failed: {str(e)}", exc_info=True)
        db.execute(
            "UPDATE translate SET status='failed', failed_reason=%s WHERE id=%s",
            str(e), trans['id']
        )
        return False


def translate_pdf(trans):
    """Synchronous entry point"""
    # Check if already in event loop
    try:
        loop = asyncio.get_running_loop()
        # If in event loop, use run_coroutine_threadsafe
        import concurrent.futures
        with concurrent.futures.ThreadPoolExecutor() as executor:
            future = executor.submit(asyncio.run, async_translate_pdf(trans))
            return future.result()
    except RuntimeError:
        # No event loop, run directly
        return asyncio.run(async_translate_pdf(trans))


def start(trans):
    """Start PDF translation (maintains same interface as TXT translation)"""
    try:
        # Parameter validation
        original_path = Path(trans['file_path'])
        if not original_path.exists():
            raise FileNotFoundError(f"File does not exist: {trans['file_path']}")

        if not original_path.suffix.lower().endswith('.pdf'):
            raise ValueError(f"File is not PDF format: {trans['file_path']}")

        # Initialize task status
        db.execute(
            "UPDATE translate SET status='process', process=0, start_at=NOW() WHERE id=%s",
            trans['id']
        )

        # Ensure output directory exists
        os.makedirs(trans['target_path_dir'], exist_ok=True)

        # Execute translation
        success = translate_pdf(trans)

        if not success:
            raise RuntimeError("PDF translation process failed")

        return True

    except Exception as e:
        logger.error(f"PDF task initialization failed: {str(e)}")
        db.execute(
            "UPDATE translate SET status='failed', failed_reason=%s WHERE id=%s",
            str(e), trans['id']
        )
        return False
